config/routes.rb
Rails.application.routes.draw do
  

    root 'welcome#home'
    get 'about', to: 'welcome#about'
    
    resources :articles
    
    get 'signup', to: 'users#new'
    resources :users, except: [:new]
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
        belongs_to :user
        has_many :article_categories
        has_many :categories, through: :article_categories
        validates :title, presence: true, length: { minimum: 3, maximum: 50 }
        validates :description, presence: true, length: { minimum: 10, maximum: 300 }
        validates :user_id, presence: true 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def index 
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end 
    def new 
        @article = Article.new
    end 
    
    def edit 
      #  @article = Article.find(params[:id])
    end 

    def create 
       # debugger
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
        flash[:success] = "Article was successfully created" 
        redirect_to article_path(@article)
        else
            render 'new'
        end    
    end 
    
    def update 
      #  @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "Article was successfully submitted"
            redirect_to article_path(@article)
        else
            render 'edit'
        end    
    end    
    
    def show 
     #   @article = Article.find(params[:id])
    end    
    
    def destroy 
     #    @article = Article.find(params[:id])
         @article.destroy
         flash[:danger] = "Article was successfully deleted"
         redirect_to articles_path
    end 
    
    private 
        def set_article
            @article = Article.find(params[:id])
        end    
        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end
        
        def require_same_user 
            if current_user != @article.user && !current_user.admin? 
                flash[:danger] = "You can only edit or delete your own articles." 
                redirect_to root_path
            end    
                
        end     
end
=begin    
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
=end    

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                    <div class="article-title">
                         <h3><%= link_to article.title, article_path(article) %></h3>
                    </div>
                    <div class="article-body">
                        <p> <%= truncate(article.description, length: 100) %></p>
                        <div class="article-meta-details">
                            <p>
                             Created By: <%= article.user.username if article.user %>,
                                 <%= time_ago_in_words(article.created_at) %> ago,
                                 Last Updated: <%= time_ago_in_words(article.updated_at) %> ago
                            </p>
                        </div>
                    </div>
                    <% if article.categories.any? %>
                        <p>Categories: <%= render article.categories %></p>
                    <% end %>
                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                        <div class="article-actions">
                            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                            <%= link_to "Delete this article", article_path(article), method: :delete,
                            data: {confirm: "Are you sure you want to delete the article?"},
                            class: "btn btn-xs btn-danger" %>
                        </div>
                    <% end %>    
            </div>
        </div>
    </div>
    <% end %>

app/views/articles/_form.html.erb
<!--
<%#= form_for(@article) do |f| %>
  <%# if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <%# @article.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :title %><br>
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :description %><br>
    <%#= f.text_area :description %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
  -->
<%# end %>

<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
            <%= f.label :title %><br/>
            </div>
            <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
            </div>
        </div>
          <div class="form-group">
                <div class="control-label col-sm-2">
            <%= f.label :description %>
            </div>
             <div class="col-sm-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %> 
        </div>
        </div>
        
        <div class="form-group">
        <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
                
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
                <% end %>
                </div>
            </div>
        </div>    
              <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-large' %>
            </div>
        </div> 
                </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<%#= render 'shared/errors', obj: @user %>

<h1>Begin and end</h1>

app/views/articles/index.html.erb
<h1 align="center">Listing All Articles<h1>

<div align="center">
    <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<!--<h1>New Article</h1>

<%#= render 'form' %>

<%#= link_to 'Back', articles_path %>-->

<h1 align="center">Create An Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<!--<p id="notice"><%#= notice %></p>

<p>
  <strong>Title:</strong>
  <%#= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%#= @article.description %>
</p>

<%#= link_to 'Edit', edit_article_path(@article) %> |
<%#= link_to 'Back', articles_path %>
-->

<h2 align="center">Title: <%= @article.title %> </h2>
<div class="well col-xs-8 col-xs-offset-2">
<% if @article.user %>
<ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                <li>Created By:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                        <li class="article-title">
                            <%= link_to @article.user.username, user_path(@article.user) %>
                        </li>
                        <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                    </div>
                </div>
            </ul>
<% end %>            
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
        <%= simple_format(@article.description) %>
            <% if @article.categories.any? %>
                <p>Categories: <%= render @article.categories %></p>
            <% end %>
    <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article", edit_article_path, class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(@article), method: :delete,
                                                        data: {confirm: "Are you sure you want to delete the article?"},
                                                        class: "btn btn-xs btn-danger" %>
     <% end %>                                                   
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
</div>
</div>
<%#= render 'form' %>